name: deploy-app

on:
  push:
    branches:
      - main
    paths:
      - '/**'

defaults:
  run:
    working-directory: /

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run deploy
      
